name: Build

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['master']

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        java:
          - adopt@1.8
          - adopt@1.11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java and SBT
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}
      - name: Cache SBT
        uses: coursier/cache-action@v5
      - name: Run tests and coverage
        run: sbt jacocoAggregate
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v1
        if: matrix.java == 'adopt@1.8'
        with:
          file: ./target/jacoco/report/aggregate/jacoco.xml
          fail_ci_if_error: true
